public without sharing class AvoidRecursionCls {
    public static boolean isRecomended = false;// To know if the Program Rating is updated with Recomended Anual Report rating
    public static boolean isOnsiteVisit = false;// to know if the field Program Rating field is update from Inspection Onsite Rating.
    public static boolean isRunOnce = true;
    public static boolean ratingsCalculated = TRUE;
}